### ISSUE TITLE
Blank/white aircraft

### ISSUE THREAD

**Issue by ithomasq** [hallidave/simple-traffic-vpilot#2]
Hello,

First, thank you for your job. It’s works almost perfect , but I have a little issue, that some aircraft are blank/white. Actually all with icao airlnine BAW, SAS , DLH etc.
Could you check if you have this issue?

**Comment by hallidave** [comment]
Thanks. I will look into it.

**Comment by hallidave** [comment]
I'm not seeing this problem. The only white aircraft that I see are ICAO codes that are unsupported by Simple Traffic. I specifically checked for BAW aircraft at EGLL and I see it working for the aircraft types that were there (A20N, A320, etc.).

A white aircraft typically means that either the ICAO airline code and/or the aircraft type are not matched.
